const Banner = () => {
                                                                                                                        return (
                                                                                                                                                                                                                                                <section className="container mx-auto justify-center relative bg-[url(https://images.unsplash.com/photo-1604014237800-1c9102c219da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80)] bg-cover bg-center bg-no-repeat">
                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute inset-0 bg-white/75 sm:bg-transparent sm:bg-gradient-to-r sm:from-white/95 sm:to-white/25"></div>

                                                                                                                                                                                                                                                                                                                                                                        <div className="relative mx-auto max-w-screen-xl px-4 py-28 sm:px-6 lg:flex lg:h-2/3 lg:items-center lg:px-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="max-w-xl text-center sm:text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1 className="text-3xl font-extrabold sm:text-5xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                </section>
                                                                                                                        );
};

export default Banner;
